app_node_image: ubuntu-20_04-image # specify the image to use
app_node_base_flavor_name: m1.small # specify the flavor for support nodes
app_remote_user: ubuntu # specify the ssh user
app_network: mgmt # specify the network to use
app_sec_group: default # specify the security group to use
edge_name: "bdbf" # specify a name for the edge to setup
helm_version: v3.11.0 # specify the helm version to use

# Do not change the variables below, these are set for the playbooks
app_name: vios
cloud_username: "{{ lookup('env','CLOUD_USERNAME') }}"
cloud_password: "{{ lookup('env','CLOUD_PASSWORD') }}"
cloud_region: RegionOne
cloud_availability_zone: nova
cloud_auth_url: "{{ lookup('env','CLOUD_AUTH_URL') }}"
cloud_tenant_name: "{{ lookup('env','CLOUD_TENANT_NAME') }}"
cloud_key_name: ansible
master_name: "{{ app_name }}-master"
master_flavor_name: m2.medium
master_image_name: "{{ app_node_image }}"
workers_name: "{{ app_name }}-worker"
workers_image: "{{ app_node_image }}"
workers_flavor_name: "{{ app_node_base_flavor_name }}"
vyos_hub_name: "{{ app_name }}-vyos-hub"
vyos_spoke_name: "{{ app_name }}-vyos-spoke"
vyos_image: "{{ app_node_image }}"
vyos_flavor_name: "{{ app_node_base_flavor_name }}"
vyos_container_image: vyos/image:1.4-rolling
edge_node_name: "{{ app_name }}-{{ edge_name }}-edge"
edge_image: "{{ app_node_image }}"
edge_flavor_name: m2.medium
edge_proxy_name: "{{ app_name }}-{{ edge_name }}-edgeproxy"
edge_proxy_image: "{{ app_node_image }}"
edge_proxy_flavor_name: "{{ app_node_base_flavor_name }}"
cluster_network_name: "{{ app_network }}"
cluster_security_group: "{{ app_sec_group }}"
cluster_subnet_name: "{{ app_network }}"
cluster_subnet_cidr: 10.8.10.0/24
cluster_pod_subnet_cidr: 10.244.0.0/16
cluster_dns_ip: 10.96.0.10
cluster_ssh_user: "{{ app_remote_user }}"
docker_url_apt_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_repository: "deb https://download.docker.com/linux/ubuntu focal stable"
# k8s_url_apt_key: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
k8s_url_apt_key: "https://web.archive.org/web/20230223152417if_/https://packages.cloud.google.com/apt/doc/apt-key.gpg"
k8s_repository: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
helm_url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
helm_bin_dir: /opt/bin
helm_chart_url: "https://5g-victori-project.github.io/vios-helmcharts"
kubernetes_ubuntu_version: 1.21.3-00
