app_node_image: ubuntu-20_04-image
app_node_base_flavor_name: m1.small
app_node_key_flavor_name: m2.medium
app_node_region: RegionOne
app_node_az: nova
app_remote_user: ubuntu
app_network: mgmt
app_sec_group: default
cloud_key: ansible
cloud_net_provider: provider
osm_version: 13
edge_name: bdbf2


# Do not change the variables below, these are set for the roles
app_name: vios
cloud_server: "{{ lookup('env','CLOUD_SERVER') }}"
cloud_username: "{{ lookup('env','CLOUD_USERNAME') }}"
cloud_password: "{{ lookup('env','CLOUD_PASSWORD') }}"
cloud_region: "{{ app_node_region }}"
cloud_availability_zone: "{{ app_node_az }}"
cloud_auth_url: "{{ lookup('env','CLOUD_AUTH_URL') }}"
cloud_tenant_name: "{{ lookup('env','CLOUD_TENANT_NAME') }}"
cloud_key_name: "{{ cloud_key }}"
cloud_network_provider: "{{ cloud_net_provider }}"
osm_server_version: "{{ osm_version }}"
master_name: "{{ app_name }}-master"
master_flavor_name: "{{ app_node_key_flavor_name }}"
master_image_name: "{{ app_node_image }}"
workers_name: "{{ app_name }}-worker"
workers_image: "{{ app_node_image }}"
workers_flavor_name: "{{ app_node_base_flavor_name }}"
vyos_hub_name: "{{ app_name }}-vyoshub"
vyos_spoke_name: "{{ app_name }}-vyosspoke-{{ edge_name }}"
vyos_image: "{{ app_node_image }}"
vyos_flavor_name: "{{ app_node_base_flavor_name }}"
vyos_container_image: vyos/image:1.4-rolling
edge_node_name: "{{ app_name }}-edge-{{ edge_name }}"
edge_image: "{{ app_node_image }}"
edge_flavor_name: "{{ app_node_key_flavor_name }}"
edge_proxy_name: "{{ app_name }}-edgeproxy-{{ edge_name }}"
edge_proxy_image: "{{ app_node_image }}"
edge_proxy_flavor_name: "{{ app_node_base_flavor_name }}"
cluster_network_name: "{{ app_network }}"
cluster_security_group: "{{ app_sec_group }}"
cluster_subnet_name: "{{ app_network }}"
cluster_subnet_cidr: 10.8.10.0/24
cluster_pod_subnet_cidr: 10.244.0.0/16
cluster_dns_ip: 10.96.0.10
cluster_ssh_user: "{{ app_remote_user }}"
docker_url_apt_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_repository: "deb https://download.docker.com/linux/ubuntu focal stable"
# k8s_url_apt_key: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
k8s_url_apt_key: "https://web.archive.org/web/20230223152417if_/https://packages.cloud.google.com/apt/doc/apt-key.gpg"
k8s_repository: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
helm_version: v3.11.0
helm_url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
helm_bin_dir: /opt/bin
helm_chart_url: "https://5g-victori-project.github.io/vios-helmcharts"
kubernetes_ubuntu_version: 1.21.3-00
