- name: Creating openstack instance
  os_server:
    auth:
      auth_url: "{{ cloud_auth_url }}"
      username: "{{ cloud_username }}"
      password: "{{ cloud_password }}"
      project_name: "{{ cloud_tenant_name }}"
    name: "{{ cluster_name }}"
    region_name: "{{ cloud_region }}"
    availability_zone: "{{ cloud_availability_zone }}"
    image: "{{ cluster_image_name }}"
    key_name: "{{ cloud_key_name }}"
    flavor: "{{ cluster_flavor_name }}"
    nics: [ { net-name: "{{ cluster_network_name }}" } ]
    security_groups: "{{ cluster_security_groups }}"
  when: state == "present"
  register: instance

- name: Update inventory
  add_host:
    name: "{{ instance.server.name }}"
    ansible_ssh_host: "{{ instance.openstack.public_v4 }}"
    ansible_ssh_user: "{{ cluster_ssh_user }}"
    groupname: "{{ cluster_group }}"
  when: state == "present"

- name: Wait during instances boot
  tags: bootstrap
  wait_for:
    host: "{{ instance.openstack.public_v4 }}"
    port: 22
    search_regex: OpenSSH
  when: state == "present"

- name: allow 'ubuntu' to use sudo without needing a password
  lineinfile:
    dest: /etc/sudoers
    line: '{{cluster_ssh_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Allow SSH keys if we don't have them already
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan ' + instance.openstack.public_v4 ) }}"
  when: state == "present"


