---
- name: Setup new single node cluster
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        state: present
  roles:
    - config-cluster

- name: Install dependencies on cluster
  hosts: vios-cluster
  gather_facts: false
  tags:
    - bootstrap
  become: yes
  roles:
    - config-prerequisites
    - config-docker
    - config-k8s

