create_nodes: true

nodes:
  - name: vios-k8s-cluster
    meta:
      ansible_host_groups: vios_k8s_cluster
      ansible_host_vars: ansible_user->ubuntu


cloud_profile:
  os_compute_api_version: "2.1"
  os_ssh_user: ubuntu
  os_username: admin
  os_password: admin
  os_region: RegionOne
  os_availability_zone: nova
  os_network_name: mgmt
  os_tenant_name: admin
  os_key_name: ansible
  os_security_groups: default
  os_flavor_name: m1.small
  os_image_name: ubuntu-20_04-image
  os_auth_url: http://10.100.19.17:5000/v3/

ansible_host_groups_key: ansible_host_groups
ansible_host_vars_key: ansible_host_vars

cluster:
  cluster_name: 5g-vios
  cluster_cidr: "10.5.10.0/24"
  networking: routed
  enable_dhcp: true
  dns_nameservers:
    - 8.8.8.8
  node_pod_cidr:
     vios-master1-k8s: "10.5.15.0/24"
     vios-worker1-k8s: "10.5.16.0/24"

k8s:
  kube_config_file: "/var/lib/kubelet/kubeconfig"
  config_dirs:
     - "/var/lib/kubelet"
     - "/var/lib/kube-proxy"
     - "/var/lib/kube-apiserver"
     - "/etc/kubernetes"
     - "/etc/kubernetes/manifests"
     - "/etc/kubernetes/addons"
     - "/srv/kubernetes"

k8s_binary_location: "https://storage.googleapis.com/kubernetes-release/release"
k8s_apiserver_container_registry: "gcr.io/google_containers/hyperkube"
k8s_scheduler_container_registry: "gcr.io/google_containers/hyperkube"
k8s_controller_manager_container_registry: "gcr.io/google_containers/hyperkube"
etcd_container_registry: "gcr.io/google_containers/etcd"