- name: Creating edge proxy node
  os_server:
    auth:
      auth_url: "{{ cloud_auth_url }}"
      username: "{{ cloud_username }}"
      password: "{{ cloud_password }}"
      project_name: "{{ cloud_tenant_name }}"
    name: "{{ edge_proxy_name }}"
    region_name: "{{ cloud_region }}"
    availability_zone: "{{ cloud_availability_zone }}"
    image: "{{ edge_proxy_image }}"
    key_name: "{{ cloud_key_name }}"
    flavor: "{{ edge_proxy_flavor_name }}"
    nics:
      - net-name: "{{ cluster_network_name }}"
    security_groups: "{{ cluster_security_group }}"
  when: state == "present"
  register: instance

- name: Updating ansible inventory with edge proxy node
  add_host:
    name: "{{ instance.server.name }}"
    ansible_ssh_host: "{{ instance.openstack.public_v4 }}"
    ansible_ssh_user: "{{ cluster_ssh_user }}"
    groupname: edgeproxy
  when: state == "present"

- name: Waiting for edge proxy node to boot up
  tags: bootstrap
  wait_for:
    host: "{{ instance.openstack.public_v4 }}"
    port: 22
    search_regex: OpenSSH
  when: state == "present"

- name: Adding SSH keys to access edge proxy node
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan ' + instance.openstack.public_v4 ) }}"
  when: state == "present"