- name: Creating edge node
  os_server:
    auth:
      auth_url: "{{ cloud_auth_url }}"
      username: "{{ cloud_username }}"
      password: "{{ cloud_password }}"
      project_name: "{{ cloud_tenant_name }}"
    name: "{{ edge_node_name }}"
    region_name: "{{ cloud_region }}"
    availability_zone: "{{ cloud_availability_zone }}"
    image: "{{ edge_image }}"
    key_name: "{{ cloud_key_name }}"
    flavor: "{{ edge_flavor_name }}"
    nics:
      - net-name: "{{ cluster_network_name }}"
    security_groups: "{{ cluster_security_group }}"
  when: state == "present"
  register: edge

- name: Updating ansible inventory with edge node
  add_host:
    name: "{{ edge.server.name }}"
    ansible_ssh_host: "{{ edge.openstack.public_v4 }}"
    ansible_ssh_user: "{{ cluster_ssh_user }}"
    groupname: edges
  when: state == "present"

- name: Waiting for edge node to boot up
  tags: bootstrap
  wait_for:
    host: "{{ edge.openstack.public_v4 }}"
    port: 22
    search_regex: OpenSSH
  when: state == "present"

- name: Adding SSH keys to access edge node
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan ' + edge.openstack.public_v4 ) }}"
  when: state == "present"