---
- name: Creating new master node vm
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        state: present
  roles:
    - create-master

- name: Configuring master node
  hosts: master
  gather_facts: false
  tags:
    - bootstrap
  become: yes
  roles:
    - config-common
    - role: config-master
      vars:
        cluster_ip: "{{ hostvars['localhost']['instance']['openstack']['public_v4'] }}"
    - taint-master

- name: Installing vios microservices
  hosts: master
  gather_facts: false
  environment:
    K8S_AUTH_KUBECONFIG: "~/.kube/config"
  roles:
    - config-vios
