---
- name: Creating new master node vm
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        state: present
  roles:
    - create-master

- name: Creating new worker node vms
  hosts: localhost
  gather_facts: false
  roles:
    - create-worker

- name: Preparing nodes
  hosts: "master, workers"
  gather_facts: false
  become: true
  tags:
    - bootstrap
  roles:
    - config-common

- name: Configuring master node
  hosts: master
  gather_facts: false
  tags:
    - bootstrap
  become: true
  roles:
    - role: config-master
      vars:
        cluster_ip: "{{ hostvars['localhost']['instance']['openstack']['public_v4'] }}"
