---
- name: Create master node
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        state: present
  roles:
    - create-master

- name: Create worker nodes
  hosts: localhost
  gather_facts: false
  roles:
    - create-worker

- name: Prepare master and worker nodes
  hosts: "master, workers"
  gather_facts: false
  become: true
  tags:
    - bootstrap
  roles:
    - config-common

- name: Configure master node
  hosts: master
  gather_facts: false
  tags:
    - bootstrap
  become: true
  roles:
    - role: config-master
      vars:
        cluster_ip: "{{ hostvars['localhost']['instance']['openstack']['public_v4'] }}"

- name: Configure worker nodes
  hosts: workers
  gather_facts: false
  tags:
    - bootstrap
  become: true
  roles:
    - role: config-worker
      vars:
        cluster_ip: "{{ hostvars['localhost']['instance']['openstack']['public_v4'] }}"

- name: Install vios microservices
  hosts: master
  gather_facts: false
  environment:
    K8S_AUTH_KUBECONFIG: "~/.kube/config"
  roles:
    - config-vios