- name: Cluster | Get cloud configuration
  tags: bootstrap
  os_client_config:

- name: Cluster | Creating openstack instance
  os_server:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ tenant_name }}"
    name: "{{ cluster_name }}"
    region_name: "{{ region }}"
    availability_zone: "{{ availability_zone }}"
    image: "{{ image_name }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor_name }}"
    nics: [ { net-name: "{{ network_name }}" } ]
    security_groups: "{{ security_groups }}"
  when: state == "present"
  register: instance

- name: Cluster | Update inventory
  add_host:
    name: "{{ instance.server.name }}"
    ansible_ssh_host: "{{ instance.openstack.public_v4 }}"
    ansible_ssh_user: "{{ cluster_ssh_user }}"
    groupname: "{{ cluster_group }}"
  when: state == "present"

- name: Cluster | Wait during instances boot
  tags: bootstrap
  wait_for:
    host: "{{ instance.openstack.public_v4 }}"
    port: 22
    search_regex: OpenSSH
  when: state == "present"

- name: Cluster | Allow SSH keys if we don't have them already
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan ' + instance.openstack.public_v4 ) }}"
  when: state == "present"


