- name: Adding ssh user to sudoers
  lineinfile:
    dest: /etc/sudoers
    line: '{{ cluster_ssh_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Installing common support packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
      - python3-pip
    state: latest
    update_cache: true

- name: Disabling swap
  shell: |
    sudo swapoff -a
    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Adding docker GPG key
  apt_key:
    url: "{{ docker_url_apt_key }}"
    state: present

- name: Adding docker repository to apt
  apt_repository:
    repo: "{{ docker_repository }}"
    state: present

- name: Installing docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Checking docker is active
  service:
    name: docker
    state: started
    enabled: yes

- name: Checking group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding ssh user to docker group
  user:
    name: "{{ cluster_ssh_user }}"
    groups: docker
    append: yes

- name: Setting system configurations for kubernetes networking
  file:
    path: "/etc/sysctl.d/kubernetes.conf"
    state: "touch"

- name: Updating sysctl settings for kubernetes networking
  blockinfile:
    path: "/etc/sysctl.d/kubernetes.conf"
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Applying new sysctl settings
  command: sudo sysctl --system

- name: Adding kubernetes GPG key
  apt_key:
    url: "{{ k8s_url_apt_key }}"
    state: present

- name: Adding kubernetes repository to apt
  apt_repository:
    repo: "{{ k8s_repository }}"
    state: present

- name: Installing kubernetes
  shell: |
    sudo apt-get update
    sudo apt-get install -y kubelet="{{ kubernetes_ubuntu_version }}" kubeadm="{{ kubernetes_ubuntu_version }}" kubectl="{{ kubernetes_ubuntu_version }}"
    sudo apt-mark hold kubelet kubeadm kubectl

- name: Downloading helm
  unarchive:
    src: "{{ helm_url }}"
    dest: /tmp
    copy: no
  tags: download

- name: Creating the helm installation directory
  file:
    path: "{{ helm_bin_dir }}"
    state: directory

- name: Copying helm binary
  copy:
    src: /tmp/linux-amd64/helm
    dest: "{{ helm_bin_dir }}"
    mode: 0755
    remote_src: yes

- name: Creating helm soft link
  file:
    src: "{{ helm_bin_dir }}/helm"
    dest: "/usr/bin/helm"
    state: link

- name: Installing kubernetes python package
  pip:
    name: kubernetes