- name: Docker | Install support packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

- name: Docker | Add docker GPG key
  apt_key:
    url: "{{ docker_url_apt_key }}"
    state: present

- name: Docker | Add docker repository to apt
  apt_repository:
    repo: "{{ docker_repository }}"
    state: present

- name: Docker | Install docker binaries
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Docker | Check docker is active
  service:
    name: docker
    state: started
    enabled: yes

- name: Docker | Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Docker | Adding ubuntu to docker group
  user:
    name: "{{ cluster_ssh_user }}"
    groups: docker
    append: yes