- name: Installing nfs common
  shell: |
    sudo apt-get update
    sudo apt-get install -y nfs-common
    sudo apt-mark hold nfs-common

- name: Mounting nfs volume
  mount:
    path: /mnt
    src: "{{ cluster_ip }}:/nfs"
    fstype: nfs
    state: mounted

- name: Checking for existing kubelet configuration
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Joining worker to cluster
  command: "{{ hostvars[groups.master[0]]['joincommand'] }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when:
    - kubelet_conf.stat.exists == False