- name: Downloading OSM install script
  get_url:
    url: https://osm-download.etsi.org/ftp/osm-13.0-thirteen/install_osm.sh
    dest: /home/ubuntu

- name: Changing permissions on OSM install script
  file:
    dest: ./install_osm.sh
    mode: a+x

- name: Running OSM install script
  become_user: "{{ cluster_ssh_user }}"
  expect:
    command: ./install_osm.sh
    responses:
      Question:
        - y
    timeout: null
