- name: Checking for existing kubelet configuration
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Joining worker to cluster
  command: "{{ hostvars[groups.master[0]]['joincommand'] }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when:
    - kubelet_conf.stat.exists == False