---
- name: Configure edge proxy node
  hosts: edgeproxy
  gather_facts: true
  pre_tasks:
    - name: Set variables
      set_fact:
        ipv4_add: "{{ ansible_default_ipv4.address }}"
  become: true
  roles:
    - config-common
    - role: config-master
      vars:
        cluster_ip: "{{ ipv4_add }}"
    - taint-master

- name: Install EdgeProxy
  hosts: edgeproxy
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        state: false
  environment:
    K8S_AUTH_KUBECONFIG: "~/.kube/config"
  roles:
    - config-edgeproxy
