---
- name: Create edge node
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        state: present
  roles:
    - create-edge

- name: Get related host inventory
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        master: present
        spoke: present
  roles:
    - get-inventory

- name: Configure edge node
  hosts: edges
  gather_facts: false
  become: true
  roles:
    - config-edge

- name: Install EdgeProxy
  hosts: edges
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        state: present
  environment:
    K8S_AUTH_KUBECONFIG: "~/.kube/config"
  roles:
    - config-edgeproxy
    - role: update-edgeproxy
      vars:
        vim_account: "{{ hostvars[groups['edges'][0]].vim.stdout }}"
        osm_server: "{{ hostvars[groups['edges'][0]].ansible_ssh_host }}"
        epa_server: "{{ hostvars[groups['edges'][0]].ansible_ssh_host }}"
        apigateway_ip: "{{ hostvars[groups['master'][0]].ansible_ssh_host }}"
        vyos_spoke_ip: "{{ hostvars[groups['spoke'][0]].ansible_ssh_host }}"
