---
- name: Create edge proxy node
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        state: present
  roles:
    - create-edgeproxy

- name: Get related host inventory
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        master: present
        spoke: present
  roles:
    - get-inventory

- name: Configure edge proxy node
  hosts: edgeproxy
  gather_facts: false
  tags:
    - bootstrap
  become: true
  roles:
    - config-common
    - role: config-master
      vars:
        cluster_ip: "{{ hostvars[groups['edgeproxy'][0]].ansible_ssh_host }}"
    - taint-master

- name: Install EdgeProxy
  hosts: edgeproxy
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        state: false
  environment:
    K8S_AUTH_KUBECONFIG: "~/.kube/config"
  roles:
    - config-edgeproxy
    - role: update-edgeproxy
      vars:
        epa_server: "{{ hostvars[groups['edgeproxy'][0]].ansible_ssh_host }}"
        apigateway_ip: "{{ hostvars[groups['master'][0]].ansible_ssh_host }}"
        vyos_spoke_ip: "{{ hostvars[groups['spoke'][0]].ansible_ssh_host }}"
