---
- name: Get related host inventory
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        master: present
        spoke: present
  roles:
    - get-inventory
  tasks:
  - set_fact:
      vyos_spoke_ip: "{{ hostvars[groups['spoke'][0]].ansible_ssh_host }}"
      apigateway_ip: "{{ hostvars[groups['master'][0]].ansible_ssh_host }}"