---
- name: Create vyos spoke node
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set variables
      set_fact:
        state: present
  roles:
    - create-vyosspoke

- name: Config vyos spoke node
  hosts: vyos
  gather_facts: false
  become: true
  roles:
    - config-vyos-common